# Taken from https://github.com/artsy/eidolon/blob/master/Podfile.
# Yep.
inhibit_all_warnings!

platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://bitbucket.org/pocketbrain/pocketmedia-podspecs.git'

use_frameworks!


target 'PocketMediaNativeAds_Example' do
  pod "PocketMediaNativeAds", :path => "../"
  pod 'AlamofireImage', '~> 2.0'
end

target 'PocketMediaNativeAds_ExampleTests' do
  pod "PocketMediaNativeAds", :path => "../"
  pod 'AlamofireImage', '~> 2.0'
end
