excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - PocketMediaNativeAdsExample
  - PocketMediaNativeAdsTests
disabled_rules: # rule identifiers to exclude from running
 - line_length
#  - comma
#  - control_statement

