language: objective-c

#branches:
# only:
# - master

xcode_workspace: PocketMediaNativeAds.xcodeproj
xcode_scheme: PocketMediaNativeAdsTests
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3
rvm: 1.9.3

before_install:
  - gem install cocoapods
  - pod install

#script:
#- xcodebuild clean build test -project PocketMediaNativeAds.xcworkspace -scheme PocketMediaNativeAdsTests