language: objective-c
#branches:
# only:
# - master
xcode_workspace: PocketMediaNativeAds.xcworkspace
xcode_scheme: PocketMediaNativeAdsTests
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3
cache: cocoapods
podfile: Podfile
script: 'sh scripts/ci.sh'
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    on_success: never
    on_failure: change
  slack: 'pocketmedia:8WLnvDK1qVpv3IOnGJk7YEie'
    on_success: never
    on_failure: change