language: objective-c
#branches:
# only:
# - master
xcode_workspace: PocketMediaNativeAds.xcworkspace
xcode_scheme: PocketMediaNativeAdsTests
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3
#cache: cocoapods
podfile: Podfile
script: 'sh scripts/ci.sh'
before_script:
  - brew install npm
  - npm install -g codeclimate-test-reporter
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  slack:
    rooms:
      - pocketmedia:8WLnvDK1qVpv3IOnGJk7YEie#mobileapps
    on_success: change
    on_failure: change
  email:
    on_success: change
    on_failure: change
after_script:
  - CODECLIMATE_REPO_TOKEN=80aa8c2a6b87fb244b168ca72e224474ab4f4bb33c4d6df63e4dd38596908839 codeclimate-test-reporter
