language: objective-c

#branches:
# only:
# - master

xcode_workspace: PocketMediaNativeAds.xcworkspace
xcode_scheme: PocketMediaNativeAdsTests
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3
rvm: 2.2

before_install:
  - gem install cocoapods
  - pod install

script: 'sh scripts/ci.sh'