language: objective-c

#branches:
# only:
# - master

xcode_workspace: PocketMediaNativeAds.xcworkspace
xcode_scheme: PocketMediaNativeAdsTests
#osx_image: xcode7.3
#xcode_sdk: iphonesimulator9.3
osx_image: xcode7.1
xcode_sdk: iphonesimulator9.0
#rvm: 2.2
cache: cocoapods
podfile: Podfile

#before_install:
#  - gem install cocoapods
#  - pod install

script: 'sh scripts/ci.sh'