source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PocketMediaNativeAds_Example', :exclusive => true do
  pod "PocketMediaNativeAds", :path => "../"
end

target 'PocketMediaNativeAds_Tests', :exclusive => true do
  pod "PocketMediaNativeAds", :path => "../"

  
end
