platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PocketMediaNativeAds_Example' do
  pod "PocketMediaNativeAds", :path => "../"
end

target 'PocketMediaNativeAds_Tests' do
  pod "PocketMediaNativeAds", :path => "../"
end
